object fmQueryInput: TfmQueryInput
  Left = 0
  Top = 0
  BorderStyle = bsDialog
  Caption = 'fmQueryInput'
  ClientHeight = 109
  ClientWidth = 505
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Tahoma'
  Font.Style = []
  Position = poMainFormCenter
  OnClose = FormClose
  OnShow = FormShow
  TextHeight = 14
  object lNameField: TLabel
    AlignWithMargins = True
    Left = 8
    Top = 24
    Width = 61
    Height = 14
    Caption = 'lNameField:'
    Color = clWhite
    ParentColor = False
  end
  object Panel1: TPanel
    Left = 0
    Top = 68
    Width = 505
    Height = 41
    Align = alBottom
    Color = 16316664
    ParentBackground = False
    TabOrder = 0
    object bbOk: TcxButton
      AlignWithMargins = True
      Left = 232
      Top = 6
      Width = 145
      Height = 29
      Margins.Top = 5
      Margins.Bottom = 5
      Align = alRight
      Caption = #1055#1110#1076#1090#1074#1077#1088#1076#1080#1090#1080
      LookAndFeel.NativeStyle = False
      LookAndFeel.SkinName = 'MySkinWhite'
      OptionsImage.ImageIndex = 21
      TabOrder = 0
      OnClick = bbOkClick
    end
    object bbCancel: TcxButton
      AlignWithMargins = True
      Left = 383
      Top = 6
      Width = 118
      Height = 29
      Margins.Top = 5
      Margins.Bottom = 5
      Align = alRight
      Caption = #1057#1082#1072#1089#1091#1074#1072#1090#1080
      LookAndFeel.NativeStyle = False
      LookAndFeel.SkinName = 'MySkinWhite'
      OptionsImage.ImageIndex = 10
      TabOrder = 1
      OnClick = bbCancelClick
    end
  end
end
